services:
  dhcpd:
    image: dhcpd:latest
    container_name: dhcpd
    network_mode: host
    privileged: true
    command: /bin/start_dhcpd.sh
    environment: 
      - INTERFACE=wlan1
      - IP_ADDR=192.168.200.1
      - SUBNET=192.168.200.0
      - SUBNET_CIDR=/24
