services:

  hostapd:
    image: hostapd:latest
    container_name: hostapd
    network_mode: host
    privileged: true
    command: /bin/start_hostapd.sh
    environment:
      - AP_INTERFACE=wlan1
      - OUTBOUND_INTERFACE=wlan0
      - SSID=poop-dollah

