services:

  nodogsplash:
    image: nodogsplash:latest
    container_name: nodog
    network_mode: host
    privileged: true
    command: /bin/start_nodogsplash.sh
    environment:
      - IP_ADDRESS=192.168.200.1
      - NETWORK=192.168.200.0
      - NETWORK_CIDR=/24
      - GATEWAY_INTERFACE=wlan1

